version: 2

models:
  - name: risk_solutions
    config:
      contract:
        enforced: true
      public: true
    description: "Detailed information about alternative risk solutions"
    columns:
      - name: solution_id
        description: "Unique identifier for each risk solution"
        data_type: varchar
        constraints:
          - type: not_null
          - type: unique
      - name: customer_id
        description: "Unique identifier for each customer"
        data_type: varchar
        constraints:
          - type: not_null
        meta:
          contains_pii: true
      - name: solution_type
        description: "Type of alternative risk solution"
        data_type: varchar
      - name: risk_amount
        description: "Amount of risk covered by the solution"
        data_type: number(38,2)
      - name: start_date
        description: "Solution start date"
        data_type: date
      - name: end_date
        description: "Solution end date"
        data_type: date
      - name: underwriter_id
        description: "Identifier of the underwriter responsible for the solution"
        data_type: varchar
      - name: annual_fee
        description: "Annual fee for the risk solution"
        data_type: number(38,2)

  - name: monthly_risk_exposure
    config:
      contract:
        enforced: true
      public: true
    description: "Monthly summary of risk exposure by solution type"
    columns:
      - name: month
        description: "Month of the summary"
        data_type: date
        constraints:
          - type: not_null
      - name: solution_type
        description: "Type of alternative risk solution"
        data_type: varchar
      - name: total_risk_exposure
        description: "Total risk amount for the month and solution type"
        data_type: number(38,2)
      - name: avg_risk_amount
        description: "Average risk amount for the month and solution type"
        data_type: number(38,2)
      - name: active_customers
        description: "Number of unique customers with solutions in the month and solution type"
        data_type: number
      - name: total_annual_fees
        description: "Total annual fees for the month and solution type"
        data_type: number(38,2)

  - name: customer_risk_profile
    description: "Summary of risk solutions for each customer"
    columns:
      - name: customer_id
        description: "Unique identifier for each customer"
        data_type: varchar
        constraints:
          - type: not_null
          - type: unique
        meta:
          contains_pii: true
      - name: total_solutions
        description: "Total number of risk solutions for the customer"
        data_type: number
      - name: total_risk_exposure
        description: "Total risk amount across all solutions for the customer"
        data_type: number(38,2)
      - name: avg_annual_fee
        description: "Average annual fee across all solutions for the customer"
        data_type: number(38,2)
      - name: earliest_solution_date
        description: "Start date of the customer's earliest risk solution"
        data_type: date
      - name: latest_solution_date
        description: "End date of the customer's latest risk solution"
        data_type: date